name: MyWorkflow
on: push
jobs:
  PrintMsg:
    runs-on: ubuntu-latest
    steps:
      - run :  echo "This is Job1 - to print msg in git hub action workflow."
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building App"
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing Application"