name: MyWorkflow with filter
on:
  push:
    paths:
      - 'src/**'

jobs:
  InitialJob:
    runs-on: windows-latest
    steps:
      - run :  echo "job Triggered because a file inside src/ changed."
  Build:
    needs: InitialJob
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building App"
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing Application"
  Package:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - run : echo "packaging application";

  check-git:
    runs-on: ubuntu-latest
    steps:
      - name: check git
        run: git --version
  checkout-clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: List files
        run : ls -la
